tarantool/small

.travis.yml, rpm/small.spec, test/mempool.c
Fix Centos6 build failed
CentOS 6 is completely removed on external resources.
We were able to build the image using the archives
on the Vault mirror sites, but we didn't find everything
there. We use devtoolset 7 instead,
but devtoolset-7-gcc on CentOS 6 does not provide gcc
Closes #31
=> Fix Centos6 build failed

small/lf_lifo.h, small/quota.h
Inside loops, a spurious version of compare_exchange_* should be used
(compare_exchange_weak): on some architectures non-spurious
(compare_exchange_strong) version requires overhead in implementation,
but inside loops, spurious fail doesn't break correctness.
Closes #29
=> replace strong cas with weak version inside loops

include/small/lsregion.h
lsregion header had an operation trying to subtract 2 void
pointers. Apple clang++ complained it is not valid. So the patch
turns it into char pointer arithmetics.
It didn't break before probably because lsregion.h wasn't included
into any .cc file.
---
I noticed it during multithreaded applier review. It does not compile locally.
=> lsregion: fix pointer arithmetics on apple clang++

include/small/slab_cache.h
When `slab_get` is called from `region_alloc` or `ibuf_alloc` first
of all we try to calculate order of appropriate slab. But there is
no check that requested size with slab meta is <= UINT32_MAX, that
leads to assertion failer in `slab_order` function. Add appropriate
check to `slab_get` function, now we return NULL for such big size.
=> small: fix assertion during slab allocation

CMakeLists.txt
Update minimal version to 2.8.12 to avoid
deprecation warning.
Closes #44
=> build: fix CMake warning

small/slab_arena.c
Asserts are disabled in the Release build, that leads to:
```
$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-Werror
$ make
[  6%] Building C object src/lib/small/CMakeFiles/small.dir/small/slab_arena.c.o
src/lib/small/small/slab_arena.c:220:9: error: variable 'total' set but not used [-Werror,-Wunused-but-set-variable]
size_t total = 0;
^
```
=> small: fix compilation on macOS 12

CMakeLists.txt, include/small/region.h, include/small/util.h, small/region.c, test/region.c, test/region.result
Callbacks are intented to be used in tracking allocation/truncation to provide backtrace info when leak is found. Poisoning is intended to find use-after-free cases.
In RegionGuard `trigger` is intended to truncate region before exiting current scope to save memory in case of more allocation in the same scope. `arm` is intended to reuse same guard after triggering.
=> region: add sanity check tools tools

test/lf_lifo.c
```
<...>/small/test/lf_lifo.c:54:6: error: variable 'i' set but not used
[-Werror,-Wunused-but-set-variable]
int i = 0;
```
Part of https://github.com/tarantool/tarantool/issues/8110
Fixes #57
=> build: eliminate unused variable warn on clang 15

include/small/ibuf.h, test/ibuf.c, test/ibuf.result
It is used to discard data written after the given position.
Part of https://github.com/tarantool/tarantool/issues/7939
=> ibuf: add ibuf_truncate method

include/small/mempool.h, include/small/obuf.h, small/mempool.c, small/obuf.c, test/mempool.c, test/obuf.c
We check whether connection obufs are destroyed in `iproto_connection_delete` in assertion. This check is gonna be different in ASAN obuf version. Let's introduce new API function to incapsulate implementation details. For consistency with mempool we introduce `obuf_is_initialized`.
By the way let's fix `mempool_is_initialized` to return `false` after destroying for API consistency.
Part of https://github.com/tarantool/tarantool/issues/7327
Part of https://github.com/tarantool/tarantool/issues/9149
Tarantool PR for testing in CI is https://github.com/tarantool/tarantool/pull/8901. Note that testing PR tests all commits from https://github.com/tarantool/small/pull/65 but https://github.com/tarantool/small/pull/65 is based on  the commit from this PR.
=> obuf: introduce obuf_is_initialized

include/small/small_asan.h, small/small_asan.c
If there is a leaked allocation (no references from root set except for from small allocator) then we will free it on destroy and leak will not be detected by ASAN. Instead we should free all allocation based on references we have outside of allocator (for example index in case of objects in space).
Part of https://github.com/tarantool/tarantool/issues/7327
Tarantool PR for testing in CI is https://github.com/tarantool/tarantool/pull/8901. Note that testing PR tests all commits from https://github.com/tarantool/small/pull/65 but https://github.com/tarantool/small/pull/65 based on the commit from this PR.
=> asan: do not free non-freed allocation on destroy in small allocator

CMakeLists.txt, include/small/obuf.h, include/small/obuf_asan.h, small/obuf_asan.c, test/obuf.c
If ENABLE_ASAN build flag is set then obuf implementation is changed. This implementation is ASAN friendly that is it allows to do buffer overflow/underflow and use-after-free checks as well as leak checks.
Part of https://github.com/tarantool/tarantool/issues/7327
Factored out from PR https://github.com/tarantool/small/pull/65 See it for a description.
Tarantool PR for testing in CI is https://github.com/tarantool/tarantool/pull/8901. Note that testing PR tests all commits from https://github.com/tarantool/small/pull/65 but https://github.com/tarantool/small/pull/65 based on commits from this PR.
=> asan: add obuf ASAN implementation

small/slab_cache.c
`slab_get_large` and `slab_get_with_order` may return `NULL` so we should be careful in the following assertion.
Part of tarantool/tarantool#9218
=> slab: fix `NULL` ptr deref in assertion in `slab_get`

include/small/slab_cache.h
A slab may be larger than 4 GB, see `slab_get_large`, so we should use `size_t` for its capacity, not `uint32_t`.
The `uint32_t` overflow may cause assertion failures in `ibuf` when it grows larger than 4 GB.
Part of tarantool/tarantool#9218
=> slab: fix `uint32_t` overflow in `slab_capacity`

include/small/ibuf.h, small/ibuf.c, test/ibuf.c
This interface is supposed to be used to tell that we process a piece of data from the read end of the buffer and don't need it anymore.
Required for PR https://github.com/tarantool/tarantool/pull/9272
=> ibuf: introduce ibuf_consume/ibuf_consume_before API

test/matras.cc
```
test/matras.cc:271:21: error: ‘id’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
271 |         matras_touch(&local, id);
|                     ^
test/matras.cc:269:21: note: ‘id’ was declared here
269 |         matras_id_t id;
|                     ^
```
=> test: fix unused variable warning in matras test

test/CMakeLists.txt
Looks like Debian 9 CMake version is old. According to CMake documentation OBJECT library can be used in target_link_libraries since 3.12
```
CMake Error at src/lib/small/test/CMakeLists.txt:9 (target_link_libraries):
Target "small_unit" of type OBJECT_LIBRARY may not be linked into another
target.  One may link only to STATIC or SHARED libraries, or to executables
with the ENABLE_EXPORTS property set.
```
=> test: fix test build for Debian 9 and alike

include/small/small.h, include/small/small_asan.h, small/small.c, test/small_alloc.c
It returns the information about how the requested size of bytes would be allocated:
* `is_large` - True if the object is allocated on the large slab (by malloc), false if it is allocated on the mempool.
* `real_size` - Size of the memory block that is actually allocated for the requested size.
Needed for tarantool/tarantool#6762
Do not merge until https://github.com/tarantool/tarantool/pull/9228 is approved!
=> small: introduce the new method `small_alloc_info`

include/small/matras.h, small/matras.c
Commit 7aff04fe0b65 ("matras: fix `matras_view::block_count` overflow") limited the capacity of a single instance of matras to 2<sup>31</sup> blocks, however this limit is too conservative. It is actually possible to address 2<sup>32</sup> blocks, just need to make `block_count` and `capacity` fields 64-bit to avoid the overflow.
Needed for tarantool/tarantool#9864
=> matras: increase max capacity from `2^31` to `2^32` blocks

include/small/lsregion.h, include/small/lsregion_asan.h, include/small/rlist.h, small/lsregion.c, small/lsregion_asan.c, test/lsregion.c
lsregion is a good candidate for an output buffer, maybe even better
than obuf:
Obuf may be freed / flushed only completely, meaning you need two obufs
to be able to simultaneously flush one of them and write to the other.
At the same time, lsregion may be gradually freed up to the last flushed
position without blocking the incoming writes.
In order to use lsregion as an output buffer, introduce
lsregion_to_iovec method, which will simply enumerate all the allocated
slabs and their sizes and save their contents to the provided iovec
array.
Since the last flushed slab may still be used by further allocations
(which may happen while the flushed data is being written), introduce a
lsregion_svp helper struct, which tracks the last flushed position.
Last flushed slab is determined by flush_id …
=>  lsregion: introduce lsregion_to_iovec method

include/small/rlist.h, include/small/util.h, test/lsregion.c
Changed default tarantool `offsetof` macro implementation so it don't
access members of null pointer in typeof. Also fixed the same problem
in `rlist_entry_is_head`.
Needed for https://github.com/tarantool/tarantool/issues/10143
NO_DOC=bugfix
NO_CHANGELOG=minor
NO_TEST=tested manually with fuzzer
=> rlist: make foreach_enrty_* macros not to use UB

include/small/lsregion_asan.h, small/lsregion_asan.c, test/lsregion.c
lsregion_reserve() was never used separately from lsregion_alloc in our code base, so a separate lsregion_reserve() implementation for asan wasn't needed.
This is going to change, so let's implement the missing method.
Also reenable basic reserve tests for asan build.
Needed for tarantool/tarantool#10161
The asan build with tarantool is tested here: https://github.com/tarantool/tarantool/pull/9922/commits/5d368091bafccd39c2a9cf246e710f3daf3395b7 (release_asan_clang and debug_asan_clang workflows)
=> lsregion: implement lsregion_reserve for asan build

test/CMakeLists.txt
Follows up commit 55061d89473e
("test: introduce a CMake function create_test").
=> test: get rid of debug message

small/small.c, test/small_alloc.c
If alloc_factor is small so that number of small mempools is SMALL_MEMPOOL_MAX we fail to call small_mempool_create_groups() for the last group of mempools.
Needed for https://github.com/tarantool/tarantool/issues/10148
Tarantool PR with bump https://github.com/tarantool/tarantool/pull/10519
=> small: fix crash with low alloc_factor and high memory pressure

include/small/slab_cache_asan.h, test/slab_cache.c
It was 8 bytes by mistake. We should align slabs as malloc at least ie the pointer should be suitable to store any type.
Before the change the newly added test failed:
/home/shiny/dev/tarantool/src/lib/small/test/slab_cache.c:134:2: runtime error: store to misaligned address 0x521000001528 for type 'long double', which requires 16 byte alignment 0x521000001528: note: pointer points here
be be 20 00  00 10 00 00 00 00 00 00  be be be be be be be be  be be be be be be be be  be be be be
^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/shiny/dev/tarantool/src/lib/small/test/slab_cache.c:134:2 in
=> slab cache: fix slab alignment to 16 bytes

small/mempool.c
The type cast is unnecessary and causes false-positive errors:
```
./small/mempool.c:109:9: runtime error: store to misaligned address 0x79651c000074 for type 'void **', which requires 8 byte alignment 0x79651c000074: note: pointer points here
00 00 00 00 23 23 23 23  50 50 50 50 50 50 50 50  50 50 50 50 50 50 50 50  50 50 50 50 50 50 50 50
^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ./small/mempool.c:109:9
```
Needed for tarantool/tarantool#10631
=> mempool: fix UBSan errors regarding misaligned access

perf/small.cc
Fixes the assertion failure in the performance test and provides the `items_per_second` metric to be stored in Grafana if run in the Tarantool's CI.
=> Perf test fixes

include/small/lf_lifo.h, test/lf_lifo.c
ASAN report:
```
tarantool/src/lib/small/include/small/lf_lifo.h:86:59: runtime error: applying non-zero offset 1 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/shiny/dev/tarantool/src/lib/small/include/small/lf_lifo.h:86:59
```
Let's explicitly handle NULL pointer case. Also add test for implementation defined behaviour on integer to pointer conversion and back. We rely on this behaviour for ABA counter for NULL pointer.
Note that currently we globally suppress some UB issues so we do not check the fix in CI yet. Manual check is done.
Before patch, without suppressions test is failed as described above and passed after patch.
Removed suppressions:
```diff
diff --git a/cmake/compiler.cmake b/cmake/compiler.cmake
index d6db669f05..e057f0dea5 100644
--- …
```
=> lf_lifo: fix UB on pointer arithmetic with NULL

CMakeLists.txt
For CMake 4.0, compatibility with versions of CMake older than 3.5 has been removed [1]. Thus, on macOS it leads to the error on build, since Homebrew updates it to version 4.0.
This patch sets the minimum required version to 3.5 for now.
[1]: https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and-removed-features
=> cmake: update the minimum required version

include/small/lsregion.h, small/lsregion.c, test/lsregion.c
Cached slabs used to get their slab_id too early, at the moment of caching, and not at the moment of using the cache.
This didn't affect anything for normal-sized slabs, because for them the cache is always checked before trying to allocate another slab.
But in case a large slab was used, the invariant that slabs always receive a monotonically growing slab_id was broken. First, a normal slab was cached and received a slab_id = i. Then a large slab got allocated and received a slab_id = i + 1. Later a cached slab was taken with slab_id = i.
As a result mixing large and normal allocations could lead to a situation when lsregion_to_iovec couldn't flush a normal slab, because it considered it as already seen.
Let's fix this and always assign slab_ids at the moment the slabs are first used …
=> lsregion: fix mixing cached and large slabs in lsregion_to_iovec
